import type { Metadata } from 'next';
import { Exo } from 'next/font/google';
import './globals.css';
import Navbar from './_Components/Navbar/Navbar';
import Footer from './_Components/Footer/Footer';
import { Toaster } from '@/components/ui/sonner';
import MyProvider from './_Components/MyProvider/MyProvider';
import CartContextProvider from '../context/CartContext';
import WishlistContextProvider from '../context/WishListContext';
const exo = Exo({
  variable: '--font-exo',
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'FreshCart Commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exo.className} antialiased`}>
        <MyProvider>
          <CartContextProvider>
            <WishlistContextProvider>
              <Navbar />
              <Toaster
                position="top-center"
                richColors
                toastOptions={{
                  duration: 2500,
                }}
              />
              {children}
              <Footer />
            </WishlistContextProvider>
          </CartContextProvider>
        </MyProvider>
      </body>
    </html>
  );
}
